# Generated by Django 2.2.4 on 2019-08-14 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_name', models.TextField()),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('second_name', models.TextField()),
                ('gender', models.TextField()),
                ('national_id', models.TextField()),
                ('kra_pin', models.TextField()),
                ('email', models.TextField()),
                ('basic_salary', models.TextField()),
                ('allowances', models.TextField()),
                ('departmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.Department')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Payrolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.TextField()),
                ('payroll_month', models.TextField()),
                ('gross_salary', models.TextField()),
                ('nssf_deductions', models.TextField()),
                ('nhif_deductions', models.TextField()),
                ('taxable_income', models.TextField()),
                ('PAYE', models.TextField()),
                ('overtime', models.TextField()),
                ('salary_advance', models.TextField()),
                ('other_deductions', models.TextField()),
                ('net_salary', models.TextField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.Employee')),
            ],
            options={
                'db_table': 'payrolls',
            },
        ),
    ]
