# Generated by Django 2.2.4 on 2019-08-14 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolls',
            name='dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.Department'),
        ),
    ]
