# Generated by Django 2.2.4 on 2019-08-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0002_auto_20190814_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='allowances',
            field=models.DecimalField(decimal_places=2, max_digits=100000000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, max_digits=100000000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='PAYE',
            field=models.DecimalField(decimal_places=2, max_digits=100000000),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, max_digits=100000000),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, max_digits=100000000),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='nhif_deductions',
            field=models.DecimalField(decimal_places=2, max_digits=100000000),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='nssf_deductions',
            field=models.DecimalField(decimal_places=2, max_digits=100000000),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, max_digits=100000000),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='overtime',
            field=models.DecimalField(decimal_places=2, max_digits=100000000),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='salary_advance',
            field=models.DecimalField(decimal_places=2, max_digits=100000000),
        ),
        migrations.AlterField(
            model_name='payrolls',
            name='taxable_income',
            field=models.DecimalField(decimal_places=2, max_digits=100000000),
        ),
    ]
