# Generated by Django 2.2.4 on 2019-08-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0003_auto_20190815_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='allowances',
            field=models.DecimalField(decimal_places=2, max_digits=100000),
        ),
    ]
