# Generated by Django 2.2.4 on 2019-08-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0004_auto_20190815_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='allowances',
            field=models.TextField(),
        ),
    ]
